<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tabelodp_model extends CI_Model
{

    public $table = 'tabelodp';
    public $id = 'id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('reg', $q);
	$this->db->or_like('witel', $q);
	$this->db->or_like('sto', $q);
	$this->db->or_like('pd_name', $q);
	$this->db->or_like('odp_name', $q);
	$this->db->or_like('odp_index', $q);
	$this->db->or_like('f_coor', $q);
	$this->db->or_like('f_loc', $q);
	$this->db->or_like('f_olt', $q);
	$this->db->or_like('latitude', $q);
	$this->db->or_like('longitude', $q);
	$this->db->or_like('is_avail', $q);
	$this->db->or_like('is_blocking', $q);
	$this->db->or_like('is_other', $q);
	$this->db->or_like('is_reserve', $q);
	$this->db->or_like('is_service', $q);
	$this->db->or_like('is_total', $q);
	$this->db->or_like('updatedate', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('reg', $q);
	$this->db->or_like('witel', $q);
	$this->db->or_like('sto', $q);
	$this->db->or_like('pd_name', $q);
	$this->db->or_like('odp_name', $q);
	$this->db->or_like('odp_index', $q);
	$this->db->or_like('f_coor', $q);
	$this->db->or_like('f_loc', $q);
	$this->db->or_like('f_olt', $q);
	$this->db->or_like('latitude', $q);
	$this->db->or_like('longitude', $q);
	$this->db->or_like('is_avail', $q);
	$this->db->or_like('is_blocking', $q);
	$this->db->or_like('is_other', $q);
	$this->db->or_like('is_reserve', $q);
	$this->db->or_like('is_service', $q);
	$this->db->or_like('is_total', $q);
	$this->db->or_like('updatedate', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
//function get_some()
//    {
//        $query = $this->db->query("SELECT * FROM tabelodp WHERE odp IS NULL LIMIT 800; ");
//        return $query->result();
//    }
}

/* End of file Tabelodp_model.php */
/* Location: ./application/models/Tabelodp_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-08-01 01:27:53 */
/* http://harviacode.com */